apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f -
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kopano-gateway
  name: kopano-gateway
spec:
  ports:
  - name: "110"
    port: 110
    targetPort: 110
  - name: "143"
    port: 143
    targetPort: 143
  selector:
    io.kompose.service: kopano-gateway
status:
  loadBalancer: {}
