apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f -
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: kopano-ical
  name: kopano-ical
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: kopano-ical
status:
  loadBalancer: {}
