# https://github.com/docker-library/docs/tree/master/mysql
version: "3"

services:
  web:
    build: caddy/
    #image: abiosoft/caddy:0.10.4
    container_name: web
    restart: always
    privileged: true
    links:
      - kwebapp
      - kzpush
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/web:/root/.caddy
