apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f -
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
  - name: "10080"
    port: 10080
    targetPort: 80
  - name: "10443"
    port: 10443
    targetPort: 443
  - name: "2015"
    port: 2015
    targetPort: 2015
  selector:
    io.kompose.service: web
status:
  loadBalancer: {}
