version: "3.5"

services:
    coturn:
        image: instrumentisto/coturn:4.5
        command:
          - --log-file=stdout
          - --external-ip=$$(detect-external-ip)  # <- notice $$ to omit Docker Compose expansion
          - --static-auth-secret=test
          #- --Verbose
        tmpfs:
          - /var/lib/coturn
        #volumes:
          #- ./_dev/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
        network_mode: host
    kopano_kwmserver:
      environment:
        - turn_uris=turn:${FQDNCLEANED?err}:3478
        - turn_server_shared_secret=test

# this way the container is reachable via non-ssl 3478
# TODO how to get ssl cert from the rest of the stack?
# https://community.hetzner.com/tutorials/install-turn-stun-server-on-debian-ubuntu-with-coturn